#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 19, 2018 03:11:32 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Gui_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Help_Desk_Login (root)
    Gui_support.init(root, top)
    root.mainloop()

w = None
def create_Help_Desk_Login(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Help_Desk_Login (w)
    Gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Help_Desk_Login():
    global w
    w.destroy()
    w = None


class Help_Desk_Login:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 10 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("375x381+649+219")
        top.title("Help Desk Login")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.03, rely=0.03, relheight=0.75, relwidth=0.95)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=355)

        self.Entry1 = Entry(self.Frame1)
        self.Entry1.place(relx=0.51, rely=0.35,height=20, relwidth=0.35)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=124)

        self.Entry2 = Entry(self.Frame1)
        self.Entry2.place(relx=0.51, rely=0.49,height=20, relwidth=0.35)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(show="*")
        self.Entry2.configure(width=124)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.17, rely=0.32, height=31, width=74)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Username :''')
        self.Label1.configure(width=74)

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.17, rely=0.46, height=31, width=74)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Password :''')
        self.Label2.configure(width=74)

        self.but43 = Button(top)
        self.but43.place(relx=0.35, rely=0.84, height=34, width=107)
        self.but43.configure(activebackground="#d9d9d9")
        self.but43.configure(activeforeground="#000000")
        self.but43.configure(background="#d9d9d9")
        self.but43.configure(command=Gui_support.Login)
        self.but43.configure(disabledforeground="#a3a3a3")
        self.but43.configure(foreground="#000000")
        self.but43.configure(highlightbackground="#d9d9d9")
        self.but43.configure(highlightcolor="black")
        self.but43.configure(pady="0")
        self.but43.configure(text='''Login''')
        self.but43.configure(width=107)

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)








if __name__ == '__main__':
    vp_start_gui()



