#############################################################################
# Generated by PAGE version 4.12
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra45
    set site_5_0 .top37.fra45.tNo47.t0 
    set site_5_0 $site_5_0
    set site_5_1 .top37.fra45.tNo47.t1 
    set site_5_0 $site_5_1
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 600x450+537+258
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Ticket Monitor"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 425 \
        -width 575 
    vTcl:DefineAlias "$top.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $site_3_0.tNo47 \
        -width 554 -height 406 -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tNo47" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.tNo47.t0 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo47.t0" "TNotebook1_t0" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo47 add $site_3_0.tNo47.t0 \
        -padding 0 -sticky nsew -state normal -text Monitor -image {} \
        -compound left -underline -1 
    set site_5_0  $site_3_0.tNo47.t0
    ttk::progressbar $site_5_0.tPr48
    vTcl:DefineAlias "$site_5_0.tPr48" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
    listbox $site_5_0.lis50 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -height 302 -width 514 
    .top37.fra45.tNo47.t0.lis50 configure -font TkFixedFont
    .top37.fra45.tNo47.t0.lis50 insert end text
    vTcl:DefineAlias "$site_5_0.lis50" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tPr48 \
        -in $site_5_0 -x 20 -y 30 -width 510 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lis50 \
        -in $site_5_0 -x 20 -y 60 -width 514 -relwidth 0 -height 302 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.tNo47.t1 \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo47.t1" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo47 add $site_3_0.tNo47.t1 \
        -padding 0 -sticky nsew -state normal -text Commands -image {} \
        -compound left -underline -1 
    set site_5_1  $site_3_0.tNo47.t1
    button $site_5_1.but51 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 \
        -text {Mark All Client Responses As Finished} 
    vTcl:DefineAlias "$site_5_1.but51" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_1.but52 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Manual Refresh} 
    vTcl:DefineAlias "$site_5_1.but52" "Button2" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_1.but51 \
        -in $site_5_1 -x 20 -y 30 -width 217 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_1.but52 \
        -in $site_5_1 -x 280 -y 30 -width 217 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tNo47 \
        -in $site_3_0 -x 10 -y 10 -width 554 -relwidth 0 -height 406 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 10 -y 10 -width 575 -relwidth 0 -height 425 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

